ServeMeHR/Models/ServiceRequest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.FileDetails = new HashSet<FileDetail>();
            this.IndividualAssignmentHistories = new HashSet<IndividualAssignmentHistory>();
            this.ServiceRequestNotes = new HashSet<ServiceRequestNote>();
            this.StepHistories = new HashSet<StepHistory>();
            this.TeamAssignmentHistories = new HashSet<TeamAssignmentHistory>();
        }
    
        public int Id { get; set; }
        public string RequestHeading { get; set; }
        public string RequestDescription { get; set; }
        public string RequestorID { get; set; }
        public string RequestorFirstName { get; set; }
        public string RequestorLastName { get; set; }
        public string RequestorPhone { get; set; }
        public string RequestorEmail { get; set; }
        public Nullable<System.DateTime> DateTimeSubmitted { get; set; }
        public Nullable<System.DateTime> DateTimeStarted { get; set; }
        public Nullable<System.DateTime> DateTimeCompleted { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<int> RequestTypeStep { get; set; }
        public Nullable<int> Member { get; set; }
        public int Status { get; set; }
        public int Team { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileDetail> FileDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualAssignmentHistory> IndividualAssignmentHistories { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Member Member2 { get; set; }
        public virtual Priority Priority1 { get; set; }
        public virtual Priority Priority2 { get; set; }
        public virtual RequestType RequestType1 { get; set; }
        public virtual RequestType RequestType2 { get; set; }
        public virtual RequestTypeStep RequestTypeStep1 { get; set; }
        public virtual RequestTypeStep RequestTypeStep2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestNote> ServiceRequestNotes { get; set; }
        public virtual StatusSet StatusSet { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual StatusSet StatusSet1 { get; set; }
        public virtual Team Team2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepHistory> StepHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamAssignmentHistory> TeamAssignmentHistories { get; set; }
    }
}

ServeMeHR/Controllers/ServiceRequestsController.cs
using ServeMeHR.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.DirectoryServices;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ServeMeHR.Controllers
{
    public class ServiceRequestsController : Controller
    {
        private ServeMeHREntities db = new ServeMeHREntities();

        // GET: ServiceRequests
        public async Task<ActionResult> Index(string StatusType, string searchString)
        {
            IEnumerable<SelectListItem> statusitems = db.StatusTypes.Select(c => new SelectListItem
            {
                Selected = c.Id == 1,
                Value = c.StatusTypeDescription,
                Text = c.StatusTypeDescription
            });
            ViewBag.StatusType = statusitems;

            ViewBag.CurrentFilter = searchString;
            if (StatusType == null)
                StatusType = "Open";

            var serviceRequests = db.ServiceRequests.Include(s => s.Member1).Include(s => s.Priority1).Include(s => s.RequestType1).Include(s => s.RequestTypeStep1).Include(s => s.StatusSet).Include(s => s.Team1);
            serviceRequests = from sr in db.ServiceRequests
                              join ss in db.StatusSets on sr.Status equals ss.Id
                              join st in db.StatusTypes on ss.StatusType equals st.Id
                              where st.StatusTypeDescription == StatusType
                              orderby sr.DateTimeSubmitted descending
                              select sr;

            if (!String.IsNullOrEmpty(searchString))
            {
                serviceRequests = serviceRequests.Where(s => s.RequestHeading.Contains(searchString)
                                       || s.RequestDescription.Contains(searchString));
            }

            return View(await serviceRequests.ToListAsync());
        }

        // GET: ServiceRequests/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.FileUp = db.ApplicConfs.Select(s => s.FileSystemUpload).FirstOrDefault();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = await db.ServiceRequests.FindAsync(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            return View(serviceRequest);
        }

        // GET: ServiceRequests/Create
        public ActionResult Create()
        {
            List<Team> lstTeam = db.Teams.ToList();
            ViewBag.Team = new SelectList(lstTeam, "Id", "TeamDescription");
            ViewBag.Member = new SelectList(db.Members, "Id", "MemberFullName");
            ViewBag.Priority = new SelectList(db.Priorities, "Id", "PriorityDescription");
            ViewBag.RequestType = new SelectList(db.RequestTypes, "Id", "RequestTypeDescription");
            ViewBag.RequestTypeStep = new SelectList(db.RequestTypeSteps, "Id", "StepDescription");
            ViewBag.Status = new SelectList(db.StatusSets, "Id", "StatusDescription");

            string homePhone;
            string givenName;
            string surname;
            string email;

            var model = new ServiceRequest();
            model.RequestorID = User.Identity.Name;
            ViewBag.FileUp = db.ApplicConfs.Select(s => s.FileSystemUpload).FirstOrDefault();

            Boolean ADconf = db.ApplicConfs.Select(s => s.ADActive).FirstOrDefault();

            if (ADconf)
            {
                GetADinfo(out givenName, out surname, out homePhone, out email);

                model.RequestorFirstName = givenName;
                model.RequestorLastName = surname;
                model.RequestorEmail = email;
                model.RequestorPhone = homePhone;
                model.RequestType = 1;
            }

            return View(model);
        }

        // POST: ServiceRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,RequestHeading,RequestDescription,RequestorID,RequestorFirstName,RequestorLastName,RequestorPhone,RequestorEmail,DateTimeSubmitted,DateTimeStarted,DateTimeCompleted,Priority,RequestType,RequestTypeStep,Member,Status,Team,RowVersion")] ServiceRequest serviceRequest)
        {
            if (ModelState.IsValid)
            {
                string homePhone;
                string givenName;
                string surname;
                string email;

                ////=============================================================================
                ViewBag.RequestTypeStep = new SelectList(db.RequestTypeSteps, "Id", "StepDescription");
                ViewBag.Status = new SelectList(db.StatusSets, "Id", "StatusDescription");

                Boolean ADconf = db.ApplicConfs.Select(s => s.ADActive).FirstOrDefault();

                if (ADconf)
                {
                    GetADinfo(out givenName, out surname, out homePhone, out email);
                    ViewBag.RequestorFirstName = givenName;
                    ViewBag.RequestorLastName = surname;
                    ViewBag.RequestorPhone = homePhone;
                    ViewBag.RequestorEmail = email;
                }

                //Attached File Processing========================================================

                List<FileDetail> fileDetails = new List<FileDetail>();
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        FileDetail fileDetail = new FileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid()
                        };
                        fileDetails.Add(fileDetail);

                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);
                    }
                }

                serviceRequest.FileDetails = fileDetails;

                //================================================================================

                //================================================================================
                // add service request
                db.ServiceRequests.Include(i => i.IndividualAssignmentHistories).Include(i => i.TeamAssignmentHistories).Include(i => i.FileDetails);
                db.ServiceRequests.Add(serviceRequest);
                serviceRequest.DateTimeSubmitted = DateTime.Now;
                serviceRequest.Status = 1;
                serviceRequest.RequestorID = User.Identity.Name;
                //serviceRequest.RequestorFirstName = givenName;
                //serviceRequest.RequestorLastName = surname;
                //serviceRequest.RequestorPhone = homePhone;
                //serviceRequest.RequestorEmail = email;

                //================================================================================
                //Create a history record for team assignment

                serviceRequest.TeamAssignmentHistories.Add(new TeamAssignmentHistory()
                {
                    DateAssigned = DateTime.Now,
                    AssignedBy = User.Identity.Name,
                    ServiceRequest = serviceRequest.Id,
                    Team = serviceRequest.Team
                });
                //================================================================================

                //================================================================================
                //Create history record for individual assignment
                serviceRequest.IndividualAssignmentHistories.Add(new IndividualAssignmentHistory()
                {
                    DateAssigned = DateTime.Now,
                    AssignedBy = User.Identity.Name,
                    //AssignedTo = "A3HR.Lyndon",
                    AssignedTo = serviceRequest.Member.Value,
                    ServiceRequest = serviceRequest.Id,
                });
                //================================================================================

                //Create request step history record===============================================
                serviceRequest.StepHistories.Add(new StepHistory()
                {
                    LastUpdated = DateTime.Now,
                    RequestTypeStep = serviceRequest.RequestTypeStep.Value,
                    ServiceRequest = serviceRequest.Id
                });

                //=================================================================================

                await db.SaveChangesAsync();
                //Check and see if in application configuration email confirmation is set on========
                Boolean emailconf = db.ApplicConfs.Select(s => s.EmailConfirmation).FirstOrDefault();

                if (emailconf)
                {
                    SendStatusConfirmation(1, serviceRequest.RequestorEmail);
                }
                //=================================================================================

                return RedirectToAction("Index");
            }

            ViewBag.Member = new SelectList(db.Members, "Id", "MemberUserid", serviceRequest.Member);

ServeMeHR/Views/ServiceRequests/Create.cshtml
@model ServeMeHR.Models.ServiceRequest

@{
    ViewBag.Title = "Create";
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        if ($("#Team").val() == '0') {
            var requestTypeDefaultValue = "<option value='0'>--Select a team first--</option>";
            $("#RequestType").html(requestTypeDefaultValue).show();
            var prioritiesDefaultValue = "<option value='0'>--Select a team first--</option>";
            $("#Priority").html(prioritiesDefaultValue).show();
            var membersDefaultValue = "<option value='0'>--Select a team first--</option>";
            $("#Member").html(membersDefaultValue).show();
        }

        $("#Team").change(function () {
            var selectedItemValue = $(this).val();

            var ddlRequestTypes = $("#RequestType");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetRequestTypeByTeam", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlRequestTypes.html('');
                    $.each(data, function (id, option) {
                        ddlRequestTypes.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load request types!!.');
                }
            });

            var ddlPriorities = $("#Priority");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetPrioritiesByTeam", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlPriorities.html('');
                    $.each(data, function (id, option) {
                        ddlPriorities.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load priorities!!.');
                }
            });

            var ddlMembers = $("#Member");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetMembersByTeam", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlMembers.html('');
                    $.each(data, function (id, option) {
                        ddlMembers.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load members!!.');
                }
            });

            var ddlRequestTypeSteps = $("#RequestTypeStep");

            var selectedItemValue2 = 1;
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetRequestTypeStepsByRequestType", "ServiceRequests")',
                data: { "id": selectedItemValue2 },
                success: function (data) {
                    ddlRequestTypeSteps.html('');
                    $.each(data, function (id, option) {
                        ddlRequestTypeSteps.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load request type steps!!.');
                }
            });

        });

        $("#RequestType").change(function () {
            var selectedItemValue = $(this).val();

            var ddlRequestTypeSteps = $("#RequestTypeStep");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetRequestTypeStepsByRequestType", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlRequestTypeSteps.html('');
                    $.each(data, function (id, option) {
                        ddlRequestTypeSteps.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load request type steps!!.');
                }
            });
        });

    });
</script>

<h2>Create</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create", "ServiceRequests", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h4>ServiceRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestHeading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestHeading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestHeading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.RequestDescription, new { htmlAttributes = new { @class = "form-control" }, @cols = 80, @rows = 10 })
                @Html.ValidationMessageFor(model => model.RequestDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.DateTimeSubmitted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateTimeSubmitted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTimeSubmitted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.DateTimeStarted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateTimeStarted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTimeStarted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.DateTimeCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateTimeCompleted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTimeCompleted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Team, "Team", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Team", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Team, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, "Priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Priority", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestType, "RequestType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestTypeStep, "RequestTypeStep", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestTypeStep", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestTypeStep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Member, "Member", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Member", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Member, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewBag.FileUp == true)
        {
            <div class="editor-label">
                <label>Files:</label>
            </div>
            <div class="editor-field">
                <input type="file" name="file" multiple="multiple" />
            </div>

        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

ServeMeHR/Views/ServiceRequests/Delete.cshtml
@model ServeMeHR.Models.ServiceRequest

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServiceRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestHeading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestHeading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeSubmitted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeSubmitted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeStarted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeStarted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RowVersion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RowVersion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Member1.MemberUserid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member1.MemberUserid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority1.PriorityDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority1.PriorityDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestType1.RequestTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestType1.RequestTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestTypeStep1.StepDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestTypeStep1.StepDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusSet.StatusDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusSet.StatusDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Team1.TeamDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team1.TeamDescription)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>