ServeMeHR/Controllers/TeamServiceRequestsController.cs
using ServeMeHR.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.DirectoryServices;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ServeMeHR.Controllers
{
    public class TeamServiceRequestsController : Controller
    {
        private ServeMeHREntities db = new ServeMeHREntities();

        // GET: TeamServiceRequests
        public async Task<ActionResult> Index(string StatusType, string searchString)
        {
            IEnumerable<SelectListItem> statusitems = db.StatusTypes.Select(c => new SelectListItem
            {
                Selected = c.Id == 1,
                Value = c.StatusTypeDescription,
                Text = c.StatusTypeDescription
            });
            ViewBag.StatusType = statusitems;

            ViewBag.CurrentFilter = searchString;
            if (StatusType == null)
                StatusType = "Open";

            var serviceRequests = db.ServiceRequests.Include(s => s.Member1).Include(s => s.Priority1).Include(s => s.RequestType1).Include(s => s.RequestTypeStep1).Include(s => s.StatusSet).Include(s => s.Team1);
            serviceRequests = from sr in db.ServiceRequests
                              join ss in db.StatusSets on sr.Status equals ss.Id
                              join st in db.StatusTypes on ss.StatusType equals st.Id
                              join t in db.Teams on sr.Team equals t.Id
                              join tm in db.TeamMembers on t.Id equals tm.Team
                              join m in db.Members on tm.Member equals m.Id
                              orderby sr.DateTimeSubmitted descending
                              //where t.TeamDescription.Contains("HR Technology Solutions") & st.StatusTypeDescription == StatusType
                              where m.MemberUserid.Contains(User.Identity.Name) & st.StatusTypeDescription == StatusType

                              select sr;
            if (!String.IsNullOrEmpty(searchString))
            {
                serviceRequests = serviceRequests.Where(s => s.RequestHeading.Contains(searchString)
                                       || s.RequestDescription.Contains(searchString));
            }

            return View(await serviceRequests.ToListAsync());
        }

        // GET: TeamServiceRequests/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.FileUp = db.ApplicConfs.Select(s => s.FileSystemUpload).FirstOrDefault();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceRequest serviceRequest = await db.ServiceRequests.FindAsync(id);
            if (serviceRequest == null)
            {
                return HttpNotFound();
            }
            return View(serviceRequest);
        }

        // GET: ServiceRequests/Create
        public ActionResult Create()
        {
            List<Team> lstTeam = db.Teams.ToList();
            //lstTeam.Insert(0, new Models.Team { Id = 0, TeamDescription = "--Select Team--" });
            ViewBag.Team = new SelectList(lstTeam, "Id", "TeamDescription");
            ViewBag.Member = new SelectList(db.Members, "Id", "MemberFullName");
            ViewBag.Priority = new SelectList(db.Priorities, "Id", "PriorityDescription");
            ViewBag.RequestType = new SelectList(db.RequestTypes, "Id", "RequestTypeDescription");
            ViewBag.RequestTypeStep = new SelectList(db.RequestTypeSteps, "Id", "StepDescription");
            ViewBag.Status = new SelectList(db.StatusSets, "Id", "StatusDescription");

            //var components = User.Identity.Name.Split('\\');
            //var username = components.Last();
            //// create LDAP connection object
            //DirectoryEntry myLdapConnection = createDirectoryEntry();

            //search for user
            string homePhone;
            string givenName;
            string surname;
            string email;
            //DirectorySearcher search = new DirectorySearcher(myLdapConnection);
            //search.Filter = "(cn=" + username + ")";
            //SearchResult result = search.FindOne();
            //DirectoryEntry dsresult = result.GetDirectoryEntry();
            //givenName = dsresult.Properties["givenName"][0].ToString();
            //surname = dsresult.Properties["sn"][0].ToString();
            //email = dsresult.Properties["mail"][0].ToString();
            //homePhone = dsresult.Properties["homePhone"][0].ToString();

            var model = new ServiceRequest();
            model.RequestorID = User.Identity.Name;
            ViewBag.FileUp = db.ApplicConfs.Select(s => s.FileSystemUpload).FirstOrDefault();

            Boolean ADconf = db.ApplicConfs.Select(s => s.ADActive).FirstOrDefault();

            if (ADconf)
            {
                GetADinfo(out givenName, out surname, out homePhone, out email);

                model.RequestorFirstName = givenName;
                model.RequestorLastName = surname;
                model.RequestorEmail = email;
                model.RequestorPhone = homePhone;
                model.RequestType = 1;
            }

            return View(model);
        }

        // POST: ServiceRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,RequestHeading,RequestDescription,RequestorID,RequestorFirstName,RequestorLastName,RequestorPhone,RequestorEmail,DateTimeSubmitted,DateTimeStarted,DateTimeCompleted,Priority,RequestType,RequestTypeStep,Member,Status,Team,RowVersion")] ServiceRequest serviceRequest)
        {
            if (ModelState.IsValid)
            {
                string homePhone;
                string givenName;
                string surname;
                string email;
                ////=============================================================================

                ViewBag.RequestTypeStep = new SelectList(db.RequestTypeSteps, "Id", "StepDescription");
                ViewBag.Status = new SelectList(db.StatusSets, "Id", "StatusDescription");

                Boolean ADconf = db.ApplicConfs.Select(s => s.ADActive).FirstOrDefault();

                if (ADconf)
                {
                    GetADinfo(out givenName, out surname, out homePhone, out email);
                    ViewBag.RequestorFirstName = givenName;
                    ViewBag.RequestorLastName = surname;
                    ViewBag.RequestorPhone = homePhone;
                    ViewBag.RequestorEmail = email;
                }

                //Attached File Processing========================================================

                List<FileDetail> fileDetails = new List<FileDetail>();
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        FileDetail fileDetail = new FileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid()
                        };
                        fileDetails.Add(fileDetail);

                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);
                    }
                }

                serviceRequest.FileDetails = fileDetails;

                //================================================================================

                //================================================================================
                // add service request
                db.ServiceRequests.Include(i => i.IndividualAssignmentHistories).Include(i => i.TeamAssignmentHistories).Include(i => i.FileDetails);
                db.ServiceRequests.Add(serviceRequest);
                serviceRequest.DateTimeSubmitted = DateTime.Now;
                serviceRequest.Status = 1;
                serviceRequest.RequestorID = User.Identity.Name;
                //serviceRequest.RequestorFirstName = givenName;
                //serviceRequest.RequestorLastName = surname;
                //serviceRequest.RequestorPhone = homePhone;
                //serviceRequest.RequestorEmail = email;

                //================================================================================
                //Create a history record for team assignment

                serviceRequest.TeamAssignmentHistories.Add(new TeamAssignmentHistory()
                {
                    DateAssigned = DateTime.Now,
                    AssignedBy = User.Identity.Name,
                    ServiceRequest = serviceRequest.Id,
                    Team = serviceRequest.Team
                });
                //================================================================================

                //================================================================================
                //Create history record for individual assignment
                serviceRequest.IndividualAssignmentHistories.Add(new IndividualAssignmentHistory()
                {
                    DateAssigned = DateTime.Now,
                    AssignedBy = User.Identity.Name,
                    //AssignedTo = "A3HR.Lyndon",
                    AssignedTo = serviceRequest.Member.Value,

ServeMeHR/Views/TeamServiceRequests/Create.cshtml
@model ServeMeHR.Models.ServiceRequest

@{
    ViewBag.Title = "Create";
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        if ($("#Team").val() == '0') {
            var requestTypeDefaultValue = "<option value='0'>--Select a team first--</option>";
            $("#RequestType").html(requestTypeDefaultValue).show();
            var prioritiesDefaultValue = "<option value='0'>--Select a team first--</option>";
            $("#Priority").html(prioritiesDefaultValue).show();
            var membersDefaultValue = "<option value='0'>--Select a team first--</option>";
            $("#Member").html(membersDefaultValue).show();
        }

        $("#Team").change(function () {
            var selectedItemValue = $(this).val();

            var ddlRequestTypes = $("#RequestType");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetRequestTypeByTeam", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlRequestTypes.html('');
                    $.each(data, function (id, option) {
                        ddlRequestTypes.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load request types!!.');
                }
            });

            var ddlPriorities = $("#Priority");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetPrioritiesByTeam", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlPriorities.html('');
                    $.each(data, function (id, option) {
                        ddlPriorities.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load priorities!!.');
                }
            });

            var ddlMembers = $("#Member");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetMembersByTeam", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlMembers.html('');
                    $.each(data, function (id, option) {
                        ddlMembers.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load members!!.');
                }
            });

            var ddlRequestTypeSteps = $("#RequestTypeStep");

            var selectedItemValue2 = 1;
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetRequestTypeStepsByRequestType", "ServiceRequests")',
                data: { "id": selectedItemValue2 },
                success: function (data) {
                    ddlRequestTypeSteps.html('');
                    $.each(data, function (id, option) {
                        ddlRequestTypeSteps.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load request type steps!!.');
                }
            });

        });

        $("#RequestType").change(function () {
            var selectedItemValue = $(this).val();

            var ddlRequestTypeSteps = $("#RequestTypeStep");
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("GetRequestTypeStepsByRequestType", "ServiceRequests")',
                data: { "id": selectedItemValue },
                success: function (data) {
                    ddlRequestTypeSteps.html('');
                    $.each(data, function (id, option) {
                        ddlRequestTypeSteps.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Found error to load request type steps!!.');
                }
            });
        });

    });
</script>

<h2>Create</h2>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create", "TeamServiceRequests", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h4>ServiceRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestHeading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestHeading, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestHeading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.DateTimeSubmitted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateTimeSubmitted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTimeSubmitted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.DateTimeStarted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateTimeStarted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTimeStarted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.DateTimeCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateTimeCompleted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTimeCompleted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Team, "Team", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Team", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Team, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, "Priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Priority", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestType, "RequestType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestTypeStep, "RequestTypeStep", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestTypeStep", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestTypeStep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Member, "Member", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Member", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Member, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Status", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewBag.FileUp == true)
        {
            <div class="editor-label">
                <label>Files:</label>
            </div>
            <div class="editor-field">
                <input type="file" name="file" multiple="multiple" />
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

ServeMeHR/Views/TeamServiceRequests/Delete.cshtml
@model ServeMeHR.Models.ServiceRequest

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServiceRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestHeading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestHeading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestorEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestorEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeSubmitted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeSubmitted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeStarted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeStarted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTimeCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTimeCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RowVersion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RowVersion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Member1.MemberUserid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member1.MemberUserid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority1.PriorityDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority1.PriorityDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestType1.RequestTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestType1.RequestTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestTypeStep1.StepDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestTypeStep1.StepDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusSet.StatusDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusSet.StatusDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Team1.TeamDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team1.TeamDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ServeMeHR/Views/TeamServiceRequests/Index.cshtml
@model IEnumerable<ServeMeHR.Models.ServiceRequest>

@{
    ViewBag.Title = "Index";
}

<h2>My Team Assigned Service Requests</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm())
{

    <p>
        @Html.DropDownList("StatusType", "Select a Value")
    </p>
    <p>
        Find by Keyword or Phrase in Heading Or Description: @Html.TextBox("SearchString")
    </p>
    <p>
        <input type="submit" value="Search" />
    </p>

}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary list-panel" id="list-panel">
            <div class="panel-heading list-panel-heading">
                <h1 class="panel-title list-panel-title"> My Team Assigned Service Requests</h1>
            </div>
            <div class="panel-body">
                <table id="TeamServiceRequests-data-table"
                       class="table table-striped table-bordered"
                       style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.DateTimeSubmitted)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RequestHeading)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RequestorFirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RequestorLastName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RequestorPhone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RequestorEmail)
                            </th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.DateTimeSubmitted)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestHeading)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestorFirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestorLastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestorPhone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RequestorEmail)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                    @Html.ActionLink("New Comment", "Create", "ServiceRequestNotes", new { ServiceRequest = item.Id, returncontroller = "TeamServiceRequests" }, null)<br />
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            $('#TeamServiceRequests-data-table').DataTable({ "order": [[0, "desc"]] });

        });
    </script>
}